#!/usr/bin/env ruby
#^syntax detection

moduledir 'modules/thirdparty'

forge 'https://forgeapi.puppetlabs.com'


mod 'camptocamp/accounts',
  :git => 'git://github.com/camptocamp/puppet-accounts',
  :tag => '1.9.3'

mod 'puppetlabs/firewall',
    :git => 'git://github.com/puppetlabs/puppetlabs-firewall.git',
    :ref => '1.8.1'

mod 'puppetlabs/concat',
  :git => 'git://github.com/puppetlabs/puppetlabs-concat',
  :tag => '4.1.0'

mod 'stahnma/epel', 
  :git => 'git://github.com/stahnma/puppet-module-epel',
  :tag => '1.2.2'

mod 'voxpupuli/extlib',
  :git => 'git://github.com/voxpupuli/puppet-extlib',
  :tag => 'v1.1.0'

mod 'n1tr0g/gnupg',
    :git => 'git://github.com/n1tr0g/golja-gnupg.git',
    :tag => '1.2.3'

mod 'voxpupuli/hiera',
        :git => 'https://github.com/voxpupuli/puppet-hiera.git',
        :tag => 'v3.3.0'

mod 'puppetlabs/inifile',
    :git => 'git://github.com/puppetlabs/puppetlabs-inifile.git',
    :tag => '1.6.0'

mod 'yo61/logrotate',
    :git => 'git://github.com/yo61/puppet-logrotate',
    :tag => 'v1.4.0'

mod 'voxpupuli/nginx',
  :git => 'git://github.com/voxpupuli/puppet-nginx',
  :tag => 'v0.7.1'

mod 'voxpupuli/nodejs',
  :git => 'git://github.com/voxpupuli/puppet-nodejs',
  :tag => 'v3.0.0'

mod 'puppetlabs/ntp',
    :git => 'git://github.com/puppetlabs/puppetlabs-ntp',
    :tag => '6.0.0'

mod 'puppetlabs/postgresql',
  :git => 'git://github.com/puppetlabs/puppetlabs-postgresql',
  :tag => '5.2.0'

mod 'stankevich/python',
    :git => 'git://github.com/stankevich/puppet-python',
    :tag => '1.18.2'

mod 'jdowning/rbenv',
    :git => 'git://github.com/justindowning/puppet-rbenv',
    :tag => '2.2.0'

mod 'puppetlabs/ruby',
  :git => 'git://github.com/puppetlabs/puppetlabs-ruby',
  :tag => '0.6.0'

mod 'voxpupuli/selinux',
  :git => 'git://github.com/voxpupuli/puppet-selinux',
  :tag => 'v1.1.0'

mod 'voxpupuli/staging',
  :git => 'git://github.com/voxpupuli/puppet-staging',
  :tag => 'v1.0.7'

mod 'puppetlabs/stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib',
  :tag => '4.20.0'

mod 'petems/swap_file',
  :git => 'git://github.com/petems/petems-swap_file',
  :tag => 'v3.0.2'

mod 'puppetlabs/vcsrepo',
    :git => 'git://github.com/puppetlabs/puppetlabs-vcsrepo',
    :tag => '1.3.2'

mod 'NYULibraries/tct',
  :git => 'git://github.com/NYULibraries/puppet-tct'

mod 'treydock/yum_cron',
    :git => 'git://github.com/treydock/puppet-yum_cron.git',
    :tag => '2.0.0'

